### PR TITLE
ci & webapp: bootstraping

### PR DESCRIPTION
**Pull request by maurelio1234**
Next steps

- General
- [x] add CI (circleci)
- [x] add CI status badge on README
- [x] run unit and e2e tests on ci
- [x] intall chrome on circleci, so that e2e tests can run properly
- [x] target es5 again (not es2015) (see https://github.com/angular/angular-cli/issues/15493)
- [ ] migrate to vuejs
- Front end bootstraping
- [x] choose and add UI lib 
- [x] Switch to eslint instead of tslint
- [x] Configure router
- Mocking front end
- [x] mock users management screen
- [x] mock edit user screen
-  mock interaction with front/backend
- [x]  api/v1/users GET/POST
- [x] api/v1/users/{userId} GET/POST/DELETE

### CODE REVIEW

**Comment by nicolaserny** [comment]
FYI tslint is (or will be this year) deprecated ([https://github.com/palantir/tslint](https://github.com/palantir/tslint)). We should use eslint instead.

**Comment by maurelio1234** [comment]
> FYI tslint is (or will be this year) deprecated (https://github.com/palantir/tslint). We should use eslint instead.

Added a TODO

**Comment by maurelio1234** [comment]
Added DevExpress. That's what we used on the last incarnation of this project (https://github.com/Invivoo/CommunicationCenter/pull/1) there's no reason to change.

**Comment by maurelio1234** [comment]
@nicolaserny  Concerning eslint I will leave it as it is, since it seems to be an open question in Angular community (https://github.com/angular/angular-cli/issues/13732).

What I'm doing for now is running the standard command for linting (which calls tslint). When it gets adapted to work with eslint we can change the config.

**Comment by maurelio1234** [comment]
Current implementation of mocks

image

image

**Comment by maurelio1234** [comment]
Fixes #19

**Pull request merged**
